import type { Metadata } from "next";
import { Julius_Sans_One } from "next/font/google";
import ClientLayout from './ClientLayout';

// Imported fonts
const JuliusFont = Julius_Sans_One({ subsets: ["latin"], weight: ['400'] });

export const metadata: Metadata = {
  title: "Market | Games & Toys",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={JuliusFont.className}>
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}
